store_site/adminapp/urls.py
from django.urls import path
app_name = 'adminapp'

from .views import *

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/category/<int:pk>/page/<int:page>/', products, name='page'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

store_site/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

store_site/basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

store_site/mainapp/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('contact', views.contact, name='contact'),
    path('product', views.products, name='product'),
    path('product/category/<int:pk>/', views.products, name='category'),
    path('product/category/<int:pk>/page/<int:page>/', views.products, name='page'),
    path('product/product/<int:pk>/', views.product, name='product'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('orders/', include('ordersapp.urls', namespace='orders'), name='orders'),
    path('', include('social_django.urls', namespace='social')),
]

store_site/store_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

store_site/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(verbose_name='активна', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'



class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='название продукта',
        max_length=128,
    )
    short_description = models.CharField(
        verbose_name='краткое описание продукта',
        max_length=128,
        blank=True,
    )
    image = models.ImageField(
        upload_to='product_img',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} - {self.pk}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

store_site/mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, ProductCategory
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    title = 'Магазин'
    context = {
        'title': title,
    }
    return render(request, 'mainapp/index.html', context)


def contact(request):
    title = 'Контакты'
    context = {
        'title': title,
    }
    return render(request, 'mainapp/contact.html', context)


def get_hot_product(products):
    return random.sample(list(products), 1)[0]


def get_related_products(hot_product):
    related_products = Product.objects.select_related('category').filter(is_active=True,
                                                                         category__is_active=True,
                                                                         category=hot_product.category).exclude(
        pk=hot_product.pk)[:3]
    return related_products


def products(request, pk=None, page=1):
    title = 'Каталог'
    links_menu = ProductCategory.objects.filter(is_active=True)
    products = Product.objects.filter(is_active=True, category__is_active=True).order_by('name')
    hot_product = get_hot_product(products)
    related_products = get_related_products(hot_product)
    if pk is not None:
        if pk == 0:
            category = {
                'name': 'все',
                'pk': 0,
            }
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(is_active=True, category__is_active=True,
                                              category__pk=pk).order_by('name')
        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)
        context = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'related_products': related_products,
            'products': products_paginator,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products.html', context)
    context = {
        'title': title,
        'links_menu': links_menu,
        'related_products': related_products,
        'products': products,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'продукты'
    links_menu = ProductCategory.objects.filter(is_active=True)
    product = get_object_or_404(Product, pk=pk)
    related_products = get_related_products(product)
    context = {
        'title': title,
        'links_menu': links_menu,
        'related_products': related_products,
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)

store_site/mainapp/templates/mainapp/includes/inc_footer.html
<div class="container">
<div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
                <div class="social">
                    <a href="#" class="social1"></a>
                    <a href="#" class="social2"></a>
                    <a href="#" class="social3"></a>
                    <a href="#" class="social4"></a>
                </div>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email" style="margin-bottom: 30px">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
 </div>

store_site/mainapp/templates/mainapp/includes/inc_header_menu.html
{% load static %}
<a href="/" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">домой</a></li>
    <li><a href="{% url 'product' %}" class="{% if request.resolver_match.url_name == 'product' %}active{% endif %}">продукты</a></li>
    <li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">контакты</a></li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                  <a data-bs-toggle="dropdown" aria-expanded="false">
                    {{ user.first_name|default:'Пользователь' }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'auth:edit' %}">Редактировать</a></li>
                    {% if user.is_superuser %}
                      <li><a class="dropdown-item" href="admin/">Админка</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                      <li><a class="dropdown-item" href="{% url 'admin_staff:users' %}">Для персонала</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Выйти</a></li>
                  </ul>
            </div>
        </li>
    {% else %}
        <li> <a href="{% url 'auth:login' %}">войти</a> </li>
    {% endif %}
    <li>
    <a href="{% url 'basket:view' %}">
        <span>
            {% if basket %}
                {{ basket.0.total_cost|floatformat:0 }} руб
                ({{ basket.0.total_quantity }} шт )
            {% endif %}
        </span>
    </a>
    </li>
</ul>

store_site/mainapp/templates/mainapp/includes/inc_product_category_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'category' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == 0 %}active{% endif %}"> Все
            </a>
        </li>
        {% for link in links_menu %}
            <li>
                <a href="{% url 'category' link.pk %}"
                   class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active{% endif %}">{{ link.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>