store_site/adminapp/urls.py
from django.urls import path
app_name = 'adminapp'

from .views import *

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', product_create, name='product_create'),
    path('products/read/category/<int:pk>/', products, name='products'),
    path('products/read/category/<int:pk>/page/<int:page>/', products, name='page'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', product_update, name='product_update'),
    path('products/delete/<int:pk>/', product_delete, name='product_delete'),
]

store_site/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

store_site/mainapp/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('contact', views.contact, name='contact'),
    path('product', views.products, name='product'),
    path('product/category/<int:pk>/', views.products, name='category'),
    path('product/category/<int:pk>/page/<int:page>/', views.products, name='page'),
    path('product/product/<int:pk>/', views.product, name='product'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('orders/', include('ordersapp.urls', namespace='orders'), name='orders'),
    path('', include('social_django.urls', namespace='social')),
]

store_site/store_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

store_site/adminapp/models.py
from django.db import models

# Create your models here.

store_site/adminapp/forms.py
from django import forms

from mainapp.models import ProductCategory, Product


class CategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_active':
                field.widget.attrs['type'] = 'checkbox'
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

store_site/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from authapp.models import ShopUser
from django.urls import reverse, reverse_lazy
from authapp.forms import ShopUserRegisterForm
from mainapp.models import ProductCategory, Product
from authapp.forms import ShopUserEditForm
from adminapp.forms import CategoryEditForm
from adminapp.forms import ProductEditForm
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection
from django.db.models import F


def db_profile_by_type(prefix, type, queries):
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    print(f'db_profile {type} for {prefix}:')
    [print(query['sql']) for query in update_queries]


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админ. панель/ пользователи'
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#     context = {
#         'title': title,
#         'users': users_list,
#     }
#     return render(request, 'adminapp/users.html', context)

class UserListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'users'

    def get_queryset(self):
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    def get_context_data(self):
        context = super(UserListView, self).get_context_data()
        title = 'админка/пользователи'
        context.update({'title': title})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_create(request):
#     title = 'пользователи/создать'
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#     context = {
#         'title': title,
#         'form': user_form
#     }
#     return render(request, 'adminapp/user_update.html', context)


class UserCreateView(LoginRequiredMixin, CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self):
        context = super(UserCreateView, self).get_context_data()
        title = 'пользователи/создать'
        context.update({'title': title})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'POST':
#         edit_form = ShopUserEditForm(request.POST, request.FILES, instance=edit_user)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserEditForm(instance=edit_user)
#     content = {
#         'title': title,
#         'form': edit_form
#     }
#     return render(request, 'adminapp/user_update.html', content)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    form_class = ShopUserEditForm

    def get_context_data(self):
        context = super(UserUpdateView, self).get_context_data()
        title = 'пользователи/редактирование'
        context.update({'title': title})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def user_delete(request, pk):
#     user = get_object_or_404(ShopUser, pk=pk)
#     if request.method == 'GET':
#         user.is_active = False if user.is_active else True
#         user.save()
#     return HttpResponseRedirect(reverse('admin_staff:users'))

class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = ShopUser
    success_url = reverse_lazy('admin_staff:users')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False if self.object.is_active else True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# @user_passes_test(lambda u: u.is_superuser)
# def categories(request):
#     title = 'админка/категории'
#     categories_list = ProductCategory.objects.all().order_by('-is_active')
#     content = {
#         'title': title,
#         'categories': categories_list
#     }
#     return render(request, 'adminapp/categories.html', content)


class ProductCategoryListView(LoginRequiredMixin, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return ProductCategory.objects.all().order_by('-is_active')

    def get_context_data(self):
        context = super(ProductCategoryListView, self).get_context_data()
        title = 'админка/категории'
        context.update({'title': title})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/создание'
#     if request.method == 'POST':
#         user_form = CategoryEditForm(request.POST)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:categories'))
#     else:
#         user_form = CategoryEditForm()
#     content = {'title': title, 'form': user_form}
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = CategoryEditForm

    def get_context_data(self):
        context = super(ProductCategoryCreateView, self).get_context_data()
        title = 'категории/создание'
        context.update({'title': title})
        return context


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = CategoryEditForm(request.POST, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:category_update', args=[edit_category.pk]))
#     else:
#         edit_form = CategoryEditForm(instance=edit_category)
#     content = {'title': title, 'update_form': edit_form}
#     return render(request, 'adminapp/category_update.html', content)


class ProductCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = CategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'GET':
#         category.is_active = False if category.is_active else True
#         category.save()
#     return HttpResponseRedirect(reverse('admin_staff:categories'))


class ProductCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin_staff:categories')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False if self.object.is_active else True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk, page=1):
    title = 'админка/продукт'
    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('-is_active', 'name')
    paginator = Paginator(products_list, 3)
    try:
        products_list_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_list_paginator = paginator.page(1)
    except EmptyPage:
        products_list_paginator = paginator.page(paginator.num_pages)
    context = {
        'title': title,
        'category': category,
        'products': products_list_paginator,
    }
    return render(request, 'adminapp/products.html', context)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'продукты/создание'
    category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()

store_site/adminapp/templates/adminapp/base.html
{% load static %}
{% load my_tags %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'mainapp/fonts/font-awesome/css/font-awesome.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    {% block css %}
    {% endblock %}

    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script src='{% static "adminapp/js/admin_script.js" %}'></script>
    {% block js %}
    {% endblock %}

</head>
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
        <div class="header_img"> <img src="{{ user.avatar | media_folder_users}}" alt=""> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div> <a href="{% url 'home' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">На главную</span>
            </a>
                <div class="nav_list">
                    {% include 'adminapp/includes/inc_menu.html' %}
                </div>
            </div>
            <a href="{% url 'auth:logout' %}" class="nav_link">
                <i class='bx bx-log-out nav_icon'></i>
                <span class="nav_name">Выход</span>
            </a>
        </nav>
    </div>
    <!--Container Main start-->
    <div class="height-100 bg-light">
        {% block content %}
        {% endblock %}
    </div>
    <!--Container Main end-->
</body>
</html>

store_site/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa fa-table mr-1"></i>
                    Список
                </div>
                <div class="card-body">
                   <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in categories %}
                            <tr bgcolor="{% if not category.is_active %}lightgrey{% endif %}">
                                <td>{{ category.name|title }}</td>
                                <td>{{ category.description|title }}</td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <a href="{% url 'admin_staff:products' category.pk %}">
                                            <button class="btn btn-success">Товары категории</button>
                                        </a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <a href="{% url 'admin_staff:category_update' category.pk %}">
                                            <button class="btn btn-success">Редактировать</button>
                                        </a>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'admin_staff:category_delete' category.pk %}">
                                        <button class="btn btn-success">Удалить/Восстановить</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


                <div class="card-footer">
                    <a href="{% url 'adminapp:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

store_site/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Категории</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Создание/редактирование
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control" type="submit" value="сохранить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

store_site/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Товары</h1>
            <div class="card" style="width: 18rem;">
                <img src="{{ product.image | media_folder_products }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <a href="{% url 'product' product.pk %}" class="btn btn-primary">Посмотреть на сайте</a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

store_site/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Редактирование/Создание
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ update_form.as_p }}
                    <input class="form-control" type="submit" value="сохранить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

store_site/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Продукты</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                {{ category.name|title }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Наименование</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Подробнее</th>
                            <th>Редактировать</th>
                            <th>Удалить/Восстановить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products %}
                        <tr bgcolor="{% if not product.is_active %}lightgrey{% endif %}">
                            <td><img src="{{ product.image | media_folder_products }}"></td>
                            <td>{{ product.name }}</td>
                            <td>{{ product.short_desc }}</td>
                            <td>{{ product.price }}</td>
                            <td>{{ product.quantity }}</td>
                            <td class="text-center">
                                {% if product.is_active %}
                                <a href="{% url 'admin_staff:product_read' product.pk %}">
                                    <button class="btn btn-success"> Подробнее</button>
                                </a>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                {% if product.is_active %}
                                <a href="{% url 'admin_staff:product_update' product.pk %}">
                                    <button class="btn btn-success"> Редактировать</button>
                                </a>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'admin_staff:product_delete' product.pk %}">
                                    <button class="btn btn-success">Удалить/Восстановить</button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="paginator">
                <h2 style="text-align: center;">
                    {% if products.has_previous %}
                    <a href="{% url 'adminapp:page' category.pk products.previous_page_number %}" style="color: black">
                        <<
                    </a>
                    {% endif %}

                    страница {{ products.number }} из
                    {{ products.paginator.num_pages }}

                    {% if products.has_next %}
                    <a href="{% url 'adminapp:page' category.pk products.next_page_number %}" style="color: black">
                        >>
                    </a>
                    {% endif %}
                </h2>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

store_site/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Создание/Редактирование
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control" type="submit" value="сохранить">
                </form>
            </div>

        </div>
    </div>
</main>
{% endblock %}

store_site/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Редактировать</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in users %}
                            <tr bgcolor="{% if not user.is_active %}lightgrey{% endif %}">
                                <td>{{ user.username }}</td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if user.is_active %}
                                        <a href="{% url 'admin_staff:user_update' user.id %}">
                                            <button class="btn btn-success">Редактировать</button>
                                        </a>
                                    {% endif %}
                                </td>
                                 <td>
                                    <a href="{% url 'admin_staff:user_delete' user.id %}">
                                        <button class="btn btn-success">Удалить/Восстановить</button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}